service: noservernovember-twitterbot

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  twitterbot:
    handler: handler.twitterbot
    events:
      - schedule: rate(4 hours)
    environment:
            TWITTER_CONSUMER_KEY: ${file(./serverless.env.yml):twitter.TWITTER_CONSUMER_KEY}
            TWITTER_CONSUMER_SECRET: ${file(./serverless.env.yml):twitter.TWITTER_CONSUMER_SECRET}
            TWITTER_ACCESS_TOKEN_KEY: ${file(./serverless.env.yml):twitter.TWITTER_ACCESS_TOKEN_KEY}
            TWITTER_ACCESS_TOKEN_SECRET: ${file(./serverless.env.yml):twitter.TWITTER_ACCESS_TOKEN_SECRET}
